### ISSUE TITLE
Failed to start child

### ISSUE THREAD

**Issue by vishal-h** [YgorCastor/ravix#12]
11:00:03.230 [info]  [RAVIX] start_link '{:via, Registry, {:request_executors, "DB/URL"}}'

11:00:03.246 [notice] Application raven exited: Raven.Application.start(:normal, []) returned an error: shutdown: failed to start child: Raven.DB.Store
    ** (EXIT) shutdown: failed to start child: Ravix.Connection
        ** (EXIT) an exception was raised:
            ** (RuntimeError) No nodes were registered successfully
                (ravix 0.1.4) lib/connection/connection_state_manager.ex:56: Ravix.Connection.State.Manager.initialize/1
                (ravix 0.1.4) lib/connection/connection.ex:24: Ravix.Connection.start_link/2
                (stdlib 3.10) supervisor.erl:379: :supervisor.do_start_child_i/3
                (stdlib 3.10) supervisor.erl:365: :supervisor.do_start_child/2
                (stdlib 3.10) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
                (stdlib 3.10) supervisor.erl:1157: :supervisor.children_map/4
                (stdlib 3.10) supervisor.erl:315: :supervisor.init_children/2
                (stdlib 3.10) gen_server.erl:374: :gen_server.init_it/2

**Comment by vishal-h** [comment]
It's failing at https://github.com/YgorCastor/ravix/blob/3b5c28a9c4c9f49c7b60d9a0bc4f5a958402a0cd/lib/connection/executor/request_executor.ex#L50

I added an additional log for `executor_id`

**Comment by vishal-h** [comment]
init call https://github.com/vishal-h/ravix/blob/d27efa86119b7cd5b75de86f7c0af9b0c212ab6f/lib/connection/executor/request_executor.ex#L32 is not made.

Not sure what the issue is. Any thoughts / suggestions?

**Comment by vishal-h** [comment]
Elixir (1.13.3)

**Comment by YgorCastor** [comment]
Can you share your configurations? Looks like it's not being able to connect to the database.

**Comment by vishal-h** [comment]
I thought so first. So tested the config with Mint. Essentially this line https://github.com/YgorCastor/ravix/blob/3b5c28a9c4c9f49c7b60d9a0bc4f5a958402a0cd/lib/connection/executor/request_executor.ex#L37 and it worked fine.

This is the last logged message on console
`[debug] [RAVIX] Registering cluster node 'https://raven.xyz.net:8080' for the store 'abc.Store'`

This message https://github.com/YgorCastor/ravix/blob/3b5c28a9c4c9f49c7b60d9a0bc4f5a958402a0cd/lib/connection/executor/request_executor.ex#L35 is not logged.

**Comment by vishal-h** [comment]
```
config :raven, ABC.Store,
  urls: ["https://raven.xyz.net:8080"],
  database: "PQR",
  certificate_file: "some_cert",
  force_create_database: false,
  document_conventions: %{
    max_number_of_requests_per_session: 30,
    max_ids_to_catch: 32,
    timeout: 30,
    use_optimistic_concurrency: false,
    max_length_of_query_using_get_url: 1024 + 512,
    identity_parts_separator: "/",
    disable_topology_update: false
  }
```

**Comment by vishal-h** [comment]
I tried the above config with certificate_file and certificate. Worked fine while using Mint

**Comment by YgorCastor** [comment]
Great, i'll check and i'll let you know

**Comment by vishal-h** [comment]
There is this bug ...
https://github.com/YgorCastor/ravix/blob/3b5c28a9c4c9f49c7b60d9a0bc4f5a958402a0cd/lib/connection/executor/request_executor.ex#L194

Parameters are passed in reverse here https://github.com/YgorCastor/ravix/blob/3b5c28a9c4c9f49c7b60d9a0bc4f5a958402a0cd/lib/connection/executor/request_executor.ex#L53

and here

https://github.com/YgorCastor/ravix/blob/3b5c28a9c4c9f49c7b60d9a0bc4f5a958402a0cd/lib/connection/executor/request_executor.ex#L115

**Comment by YgorCastor** [comment]
Thank you! 

Fixed on 0.1.5 #13 

Check and let me know!

**Comment by vishal-h** [comment]
But this works fine
```
{:ok, conn} = Mint.HTTP.connect(:https, "raven.some_url.net", 8080, transport_opts: [certfile: 'cert/elixir-raven.pfx'])
```

**Comment by vishal-h** [comment]
And this fails 
```
iex(2)>  {:ok, conn} = Mint.HTTP.connect(:https, "raven.some_url.net", 8080, transport_opts: [cacertfile: 'cert/elixir-raven.pfx'])

17:58:52.263 [notice] TLS client: In state certify at ssl_handshake.erl:1708 generated CLIENT ALERT: Fatal - Unknown CA

** (MatchError) no match of right hand side value: {:error, %Mint.TransportError{reason: {:tls_alert, {:unknown_ca, 'TLS client: In state certify at ssl_handshake.erl:1708 generated CLIENT ALERT: Fatal - Unknown CA\n'}}}}

```

**Comment by vishal-h** [comment]
Yes. I had missed the change. My bad.
Works fine now.
Thanks!
