### ISSUE TITLE
RQL/Limit issue

### ISSUE THREAD

**Issue by vishal-h** [YgorCastor/ravix#14]
I am trying out the following
```
 {:ok, session_id} = Some.Store.open_session()

    result =
      from("Txes")
      |> where(equal_to("OrgId",org_id))
      |> and?(between("TxDate",[from_date, to_date]))
      |> limit(0,1)
      |> IO.inspect()
      |> list_all(session_id)

    Some.Store.close_session(session_id)
```

The results are inconsistent. Sometimes the limit is honored and only 1 result is returned but at other times all other results are returned. 

The rql query struct(from IO.inspect) has the correct limit entry
```
%Ravix.RQL.Query{
   limit_token: %Ravix.RQL.Tokens.Limit{next: 1, skip: 0, token: :limit},
}
```

**Comment by vishal-h** [comment]
On enabling debug
```
mfa=Ravix.Connection.RequestExecutor.exec_request/6 file=lib/connection/executor/request_executor.ex line=260 [debug] [RAVIX] Executing command %Ravix.Documents.Commands.ExecuteQueryCommand{Query: "from Txes where OrgId = $p0 and TxDate between $p1 and $p2 limit 0, 1", QueryParameters: %{"p0" => "org_id", "p1" => "2022-04-01", "p2" => "2022-04-05"}, data: nil, files: [], headers: [], is_raft_request: false, is_read_request: false, method: "POST", raft_unique_request_id: nil, timeout: nil, url: nil, use_stream: false} under the request '#Reference<0.3560448815.469762049.213208>' for the store Some.Store
```

and no "CappedMaxResults" => 1,

```
 mfa=Ravix.Connection.RequestExecutor.process_response/2 file=lib/connection/executor/request_executor.ex line=327 [debug] [RAVIX] Request #Reference<0.4273357311.1564475396.23380> finished with response {:ok, %{data: %{"DurationInMs" => 1,
```
and towards the end

```
 "SkippedResults" => 0, "TotalResults" => 5},
```

**Comment by vishal-h** [comment]
Same query works fine on Raven studio. 

```
from Txes
where OrgId = "some_org_id" 
and TxDate between "2022-04-01" and "2022-04-05" 
limit 0, 1
```

**Comment by YgorCastor** [comment]
Hmm, they don't have the same Reference ID, concurrency problem maybe? I'll try to reproduce that, can you check in the logs if you have the response with the same Reference?

**Comment by vishal-h** [comment]
It has the same org_id. It's typo. Will fix that

**Comment by vishal-h** [comment]
I actually did a traffic watch on RavenDB/Studio and these are the relevant bits
```
{
    "HttpMethod": "POST",
    "ResponseStatusCode": 200,
    "RequestUri": "https://raven.some_url.net:8080/databases/some_db/queries",
    "DatabaseName": "some_db",
    "CustomInfo": "from Txes where OrgId = $p0 and TxDate between $p1 and $p2 limit 0, 1\n{\"p0\":\"org_id\",\"p1\":\"2022-04-01\",\"p2\":\"2022-04-05\"}",
    "Type": "Queries"
  }
```

**Comment by vishal-h** [comment]
Looks like the RQL is being sent correctly.

**Comment by vishal-h** [comment]
I was checking https://github.com/ravendb/ravendb/blob/v5.3/src/Raven.Studio/languageService/test/data/queries.json and noticed that all the limit queries have a trailing space like 
```
" from index 'UsersByNameWithAdditionalSources' where Name = $p0 limit $p1, $p2 ",
```
Not sure if that would make any difference

**Comment by YgorCastor** [comment]
It's not related, i'm trying to reproduce it without success until know, however it looks like the request and response you posted are not from the same query: 

The request has the reference: #Reference<0.3560448815.469762049.213208>
The Response has the reference: #Reference<0.4273357311.1564475396.23380>

can you check if you have matching request and response references in your log?

**Comment by vishal-h** [comment]
Aah I see. I don't think that's the issue. Maybe I copied from different part of the terminal. I was doing re-compile from within IEx which may have led to this.

```
under the request '#Reference<0.453672955.406061057.120866>' for the store 
```

```
mfa=Ravix.Connection.RequestExecutor.process_response/2 file=lib/connection/executor/request_executor.ex line=327 [debug] [RAVIX] Request #Reference<0.453672955.406061057.120866> finished with response 
```

But the issue is persistent

**Comment by vishal-h** [comment]
I am connecting to RavenDB 4.2.8 from a Windows 10 box. I can try from Linux with latest RavenDB and see if the issue is present.

**Comment by vishal-h** [comment]
Tried 
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

Same issue

**Comment by vishal-h** [comment]
This works fine with RavenDB 5.2.102. (Set up a db on ravendb.cloud)

Some caching issue on 4.2.8?

**Comment by vishal-h** [comment]
https://github.com/ravendb/ravendb/pull/10647

**Comment by YgorCastor** [comment]
Ahh, you are using RavenDB 4.2, i build the driver testing on 5.3, looks like a problem on the RavenDB side, yes.

**Comment by vishal-h** [comment]
Will close the ticket. Thanks for your inputs!
